name: Test Workflow  

on:  
  push:  
    branches:  
      - main  
  workflow_dispatch:  # Allows manual triggering  

jobs:  
  test:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout Repository  
        uses: actions/checkout@v4  

      - name: Print Email Address  
        run: echo "This workflow was triggered by 23f2003741@ds.study.iitm.ac.in"
